// <auto-generated />
using System;
using FHS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FHS.Api.Data.Migrations
{
    [DbContext(typeof(FhsCommandDbContext))]
    [Migration("20260903210352_AddCustomersAndEscapes")]
    partial class AddCustomersAndEscapes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FHS.Api.Data.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_actor");

                    b.HasIndex("SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_actor_subject_id");

                    b.ToTable("actor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5a5a5a5-0000-4000-8000-000000000001"),
                            DisplayName = "Line Operator",
                            SubjectId = "11111111-1111-4111-8111-111111111111",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("a5a5a5a5-0000-4000-8000-000000000002"),
                            DisplayName = "System Administrator",
                            SubjectId = "22222222-2222-4222-8222-222222222222",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_code");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ErrorCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("error_code_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_defect");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_defect_created_by");

                    b.HasIndex("ErrorCodeId")
                        .HasDatabaseName("ix_defect_error_code_id");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_defect_resolved_by");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_defect_station_id");

                    b.ToTable("defect", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.ErrorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_error_code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_error_code_code");

                    b.ToTable("error_code", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Escape", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ErrorCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("error_code_id");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_escape");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_escape_customer_id");

                    b.HasIndex("ErrorCodeId")
                        .HasDatabaseName("ix_escape_error_code_id");

                    b.HasIndex("ReportedBy")
                        .HasDatabaseName("ix_escape_reported_by");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_escape_resolved_by");

                    b.ToTable("escape", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_messages_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("messages", "outbox");
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_station");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_station_code");

                    b.ToTable("station", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Defect", b =>
                {
                    b.HasOne("FHS.Api.Data.Entities.Actor", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_defect_actor_created_by");

                    b.HasOne("FHS.Api.Data.Entities.ErrorCode", "ErrorCode")
                        .WithMany()
                        .HasForeignKey("ErrorCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_defect_error_code_error_code_id");

                    b.HasOne("FHS.Api.Data.Entities.Actor", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_defect_actor_resolved_by");

                    b.HasOne("FHS.Api.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_defect_station_station_id");

                    b.Navigation("Creator");

                    b.Navigation("ErrorCode");

                    b.Navigation("Resolver");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Escape", b =>
                {
                    b.HasOne("FHS.Api.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escape_customer_customer_id");

                    b.HasOne("FHS.Api.Data.Entities.ErrorCode", "ErrorCode")
                        .WithMany()
                        .HasForeignKey("ErrorCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escape_error_code_error_code_id");

                    b.HasOne("FHS.Api.Data.Entities.Actor", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escape_actor_reported_by");

                    b.HasOne("FHS.Api.Data.Entities.Actor", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_escape_actor_resolved_by");

                    b.Navigation("Customer");

                    b.Navigation("ErrorCode");

                    b.Navigation("Reporter");

                    b.Navigation("Resolver");
                });
#pragma warning restore 612, 618
        }
    }
}
