// <auto-generated />
using System;
using FHS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FHS.Api.Data.Migrations
{
    [DbContext(typeof(FhsCommandDbContext))]
    partial class FhsCommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FHS.Api.Data.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_actors");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_actors_facility_id");

                    b.HasIndex("SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_actors_subject_id");

                    b.ToTable("actors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5a5a5a5-0000-4000-8000-000000000001"),
                            DisplayName = "System Administrator",
                            Kind = "Person",
                            SubjectId = "11111111-1111-4111-8111-111111111111",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_code");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ErrorCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("error_code_id");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_defects");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_defects_created_by");

                    b.HasIndex("ErrorCodeId")
                        .HasDatabaseName("ix_defects_error_code_id");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_defects_resolved_by");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_defects_station_id");

                    b.HasIndex("FacilityId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_defects_facility_id_created_at")
                        .HasFilter("resolved_at IS NULL");

                    b.HasIndex("FacilityId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_defects_facility_id_created_at_id");

                    b.HasIndex("FacilityId", "ErrorCodeId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_defects_facility_id_error_code_id_created_at");

                    b.HasIndex("FacilityId", "StationId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_defects_facility_id_station_id_created_at");

                    b.ToTable("defects", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.ErrorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_error_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_error_codes_code");

                    b.ToTable("error_codes", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Escape", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttributedDefectId")
                        .HasColumnType("uuid")
                        .HasColumnName("attributed_defect_id");

                    b.Property<string>("AttributionBasis")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("attribution_basis");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ErrorCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("error_code_id");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_escapes");

                    b.HasIndex("AttributedDefectId")
                        .HasDatabaseName("ix_escapes_attributed_defect_id")
                        .HasFilter("attributed_defect_id IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_escapes_customer_id");

                    b.HasIndex("ErrorCodeId")
                        .HasDatabaseName("ix_escapes_error_code_id");

                    b.HasIndex("ReportedBy")
                        .HasDatabaseName("ix_escapes_reported_by");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_escapes_resolved_by");

                    b.HasIndex("FacilityId", "ReportedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_escapes_facility_id_reported_at")
                        .HasFilter("resolved_at IS NULL");

                    b.HasIndex("FacilityId", "CustomerId", "ReportedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_escapes_facility_id_customer_id_reported_at");

                    b.HasIndex("FacilityId", "ErrorCodeId", "ReportedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_escapes_facility_id_error_code_id_reported_at");

                    b.HasIndex("FacilityId", "ReportedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_escapes_facility_id_reported_at_id");

                    b.ToTable("escapes", null, t =>
                        {
                            t.HasCheckConstraint("ck_escapes_attribution_complete", "(attributed_defect_id IS NULL) = (attribution_basis IS NULL)");
                        });
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_facilities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_facilities_code");

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_messages_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("messages", "outbox");
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_code");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_stations_facility_id");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Actor", b =>
                {
                    b.HasOne("FHS.Api.Data.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actors_facility_facility_id");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Defect", b =>
                {
                    b.HasOne("FHS.Api.Data.Entities.Actor", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_defects_actors_created_by");

                    b.HasOne("FHS.Api.Data.Entities.ErrorCode", "ErrorCode")
                        .WithMany()
                        .HasForeignKey("ErrorCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_defects_error_code_error_code_id");

                    b.HasOne("FHS.Api.Data.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_defects_facility_facility_id");

                    b.HasOne("FHS.Api.Data.Entities.Actor", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_defects_actors_resolved_by");

                    b.HasOne("FHS.Api.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_defects_station_station_id");

                    b.Navigation("Creator");

                    b.Navigation("ErrorCode");

                    b.Navigation("Facility");

                    b.Navigation("Resolver");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Escape", b =>
                {
                    b.HasOne("FHS.Api.Data.Entities.Defect", "AttributedDefect")
                        .WithMany()
                        .HasForeignKey("AttributedDefectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_escapes_defects_attributed_defect_id");

                    b.HasOne("FHS.Api.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escapes_customers_customer_id");

                    b.HasOne("FHS.Api.Data.Entities.ErrorCode", "ErrorCode")
                        .WithMany()
                        .HasForeignKey("ErrorCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escapes_error_codes_error_code_id");

                    b.HasOne("FHS.Api.Data.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escapes_facility_facility_id");

                    b.HasOne("FHS.Api.Data.Entities.Actor", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_escapes_actors_reported_by");

                    b.HasOne("FHS.Api.Data.Entities.Actor", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_escapes_actors_resolved_by");

                    b.Navigation("AttributedDefect");

                    b.Navigation("Customer");

                    b.Navigation("ErrorCode");

                    b.Navigation("Facility");

                    b.Navigation("Reporter");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("FHS.Api.Data.Entities.Station", b =>
                {
                    b.HasOne("FHS.Api.Data.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stations_facilities_facility_id");

                    b.Navigation("Facility");
                });
#pragma warning restore 612, 618
        }
    }
}
